---
- name: Deploy Music App on Worker Node
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
     - name: Install Docker
       command: apt install docker.io -y

     - name: Start Docker service
       command: systemctl start docker

     - name: Pull latest image from DockerHub
       command: docker pull rohinicc/music-dashboard-app:latest

     - name: Remove old container if exists
       command: docker rm -f app

     - name: Run new container on port 8085
       command: docker run -d --name app -p 8085:80 rohinicc/music-dashboard-app:latest